# Generated by Django 3.2.4 on 2021-06-15 05:54

from django.db import migrations, models
import family_list_project.menagers.users


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['first_name'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', family_list_project.menagers.users.UserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='10/10/2020', max_length=50, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
