# Generated by Django 3.2.4 on 2021-06-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210615_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateField(blank=True, null=True, verbose_name='Birthday date'),
        ),
    ]
