# Generated by Django 3.2.4 on 2021-06-15 03:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('name', models.CharField(max_length=50, verbose_name='Task name')),
                ('description', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Task description')),
                ('rating', models.IntegerField(blank=True, default=None, null=True, verbose_name='Rating')),
                ('start', models.DateField(blank=True, null=True, verbose_name='Start date')),
                ('finish', models.DateField(blank=True, null=True, verbose_name='Finish date')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
