# Generated by Django 3.2.4 on 2021-06-10 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task_list', '0004_auto_20210610_1746'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('name', models.CharField(max_length=50, verbose_name='Task name')),
                ('description', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Task description')),
                ('rating', models.IntegerField(blank=True, default=None, null=True, verbose_name='Rating')),
                ('start', models.DateField(verbose_name='Start date')),
                ('finish', models.DateField(blank=True, null=True, verbose_name='Finish date')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('tasks', models.ManyToManyField(related_name='event', to='task_list.Task', verbose_name='Tasks')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
