# Generated by Django 3.2.4 on 2021-06-11 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateField(blank=True, null=True, verbose_name='Start date'),
        ),
    ]
