# Generated by Django 3.2.4 on 2021-06-25 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_list', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='owner',
        ),
    ]
