# Generated by Django 3.2.4 on 2021-06-10 02:57

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Username')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Birthday date')),
                ('gender', models.CharField(max_length=50, verbose_name='Gender')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Is super user?')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Is staff?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active?')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('name', models.CharField(max_length=50, verbose_name='Task name')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Task description')),
                ('status', models.CharField(blank=True, choices=[('CREATED', 'Created'), ('WAITING', 'Wating'), ('DONE', 'Done')], default='CREATED', max_length=10, null=True, verbose_name='Status')),
                ('rating', models.IntegerField(blank=True, default=None, null=True, verbose_name='Rating')),
                ('comments', models.CharField(blank=True, max_length=200, null=True, verbose_name='Task comments')),
                ('task_date_time', models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 10, 2, 57, 15, 12677), null=True, verbose_name='Task date')),
                ('is_concluded', models.BooleanField(default=False, verbose_name='Is concluded?')),
                ('conclusion_date', models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 10, 2, 57, 15, 12710), null=True, verbose_name='Task date')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('name', models.CharField(max_length=50, verbose_name='Family denomination')),
                ('members', models.ManyToManyField(related_name='family', to=settings.AUTH_USER_MODEL, verbose_name='Family members')),
            ],
            options={
                'verbose_name': 'Family',
                'verbose_name_plural': 'Families',
                'db_table': 'families',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('name', models.CharField(max_length=50, verbose_name='Task name')),
                ('description', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Task description')),
                ('rating', models.IntegerField(blank=True, default=None, null=True, verbose_name='Rating')),
                ('start', models.DateField(verbose_name='Start date')),
                ('finish', models.DateField(blank=True, null=True, verbose_name='Finish date')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('tasks', models.ManyToManyField(related_name='event', to='task_list.Task', verbose_name='Tasks')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
