# Generated by Django 3.2.4 on 2021-06-10 02:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='conclusion_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 10, 2, 57, 26, 110051), null=True, verbose_name='Task date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 10, 2, 57, 26, 110019), null=True, verbose_name='Task date'),
        ),
    ]
