# Generated by Django 3.2.4 on 2021-06-04 03:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_list', '0002_auto_20210604_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 4, 3, 0, 54, 518996), null=True, verbose_name='data de criação'),
        ),
    ]
