# Generated by Django 3.2.4 on 2021-06-15 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_list', '0002_task_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_date_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Task date'),
        ),
    ]
