# Generated by Django 3.2.4 on 2021-06-10 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_list', '0002_auto_20210610_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='conclusion_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 10, 16, 32, 15, 483062), null=True, verbose_name='Task date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 10, 16, 32, 15, 483031), null=True, verbose_name='Task date'),
        ),
    ]
