# Generated by Django 3.2.4 on 2021-06-10 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_list', '0003_auto_20210610_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='conclusion_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 10, 17, 46, 7, 77816), null=True, verbose_name='Task date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 10, 17, 46, 7, 77781), null=True, verbose_name='Task date'),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
