# Generated by Django 3.2.4 on 2021-06-11 01:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_list', '0004_auto_20210610_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='conclusion_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 11, 1, 39, 54, 758459), null=True, verbose_name='Task date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 11, 1, 39, 54, 758428), null=True, verbose_name='Task date'),
        ),
    ]
