# Generated by Django 3.2.4 on 2021-06-10 02:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_list', '0004_auto_20210610_0122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date',
        ),
        migrations.AddField(
            model_name='task',
            name='date_conclusion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 10, 2, 6, 43, 677610), null=True, verbose_name='Task date'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_concluded',
            field=models.BooleanField(default=True, verbose_name='Is concluded?'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 10, 2, 6, 43, 677580), null=True, verbose_name='Task date'),
        ),
    ]
