# Generated by Django 3.2.4 on 2021-06-10 02:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_list', '0005_auto_20210610_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_conclusion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 10, 2, 36, 0, 18064), null=True, verbose_name='Task date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 10, 2, 36, 0, 18031), null=True, verbose_name='Task date'),
        ),
    ]
