# Generated by Django 3.2.4 on 2021-06-11 03:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_list', '0005_auto_20210611_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='conclusion_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 11, 3, 42, 29, 318057), null=True, verbose_name='Task date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 11, 3, 42, 29, 318022), null=True, verbose_name='Task date'),
        ),
    ]
