# Generated by Django 3.2.4 on 2021-06-11 04:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_list', '0006_auto_20210611_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='conclusion_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 11, 4, 48, 12, 599715), null=True, verbose_name='Task date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 11, 4, 48, 12, 599684), null=True, verbose_name='Task date'),
        ),
    ]
