# Generated by Django 3.2.4 on 2021-06-24 23:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('families', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='members',
            field=models.ManyToManyField(related_name='family', to=settings.AUTH_USER_MODEL, verbose_name='Family members'),
        ),
    ]
